services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8084:8080"
    environment:
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_NAME: ${KEYCLOAK_CLIENT_NAME}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      AUTHENTICATION_SERVICE_URL: ${AUTHENTICATION_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}

    networks:
      - gateway_net
      - keycloak_net


networks:
  gateway_net:
  keycloak_net :
    external: true

